esphome:
  name: power-meter-9000
  friendly_name: power-meter-9000

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

api:

ota:

wifi:
  ssid: power-meter-9000
  password: power-meter-9000

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: power-meter-9000
    password: power-meter-9000

captive_portal:

uart:
  tx_pin: GPIO40
  rx_pin: GPIO39
  baud_rate: 4800
  parity: NONE
  stop_bits: 1

external_components:
    source: github://ggajoch/power-meter-9000

sensor:
  - platform: uptime
    name: Uptime
  - platform: bl0939addr
    id: ch0
    update_interval: 10s
    voltage:
      name: 'v1'
    current_1:
      name: 'c1_1'
    current_2:
      name: 'c1_2'
    active_power_1:
      name: 'p1_1'
    active_power_2:
      name: 'p1_2'
    energy_1:
      name: 'e1_1'
    energy_2:
      name: 'e1_2'
    energy_total:
      name: 'e1'
    address: 0
    current_reference: 438921.675
    voltage_reference: 16740.165
    power_reference: 1147.908
    energy_reference: 9852.572

  - platform: bl0939addr
    id: ch1
    update_interval: 10s
    voltage:
      name: 'v2'
    current_1:
      name: 'c2_1'
    current_2:
      name: 'c2_2'
    active_power_1:
      name: 'p2_1'
    active_power_2:
      name: 'p2_2'
    energy_1:
      name: 'e2_1'
    energy_2:
      name: 'e2_2'
    energy_total:
      name: 'e2'
    address: 1
    current_reference: 438921.675
    voltage_reference: 16740.165
    power_reference: 1147.908
    energy_reference: 9852.572
  
  - platform: bl0939addr
    id: ch2
    update_interval: 10s
    voltage:
      name: 'v3'
    current_1:
      name: 'c3_1'
    current_2:
      name: 'c3_2'
    active_power_1:
      name: 'p3_1'
    active_power_2:
      name: 'p3_2'
    energy_1:
      name: 'e3_1'
    energy_2:
      name: 'e3_2'
    energy_total:
      name: 'e3'
    address: 2
    current_reference: 438921.675
    voltage_reference: 16740.165
    power_reference: 1147.908
    energy_reference: 9852.572

  - platform: bl0939addr
    id: ch3
    update_interval: 10s
    voltage:
      name: 'v4'
    current_1:
      name: 'c4_1'
    current_2:
      name: 'c4_2'
    active_power_1:
      name: 'p4_1'
    active_power_2:
      name: 'p4_2'
    energy_1:
      name: 'e4_1'
    energy_2:
      name: 'e4_2'
    energy_total:
      name: 'e4'
    address: 3
    current_reference: 438921.675
    voltage_reference: 16740.165
    power_reference: 1147.908
    energy_reference: 9852.572

switch:
  - platform: gpio
    pin: 15
    name: "LED"

binary_sensor:
  - platform: gpio
    name: "button"
    pin: GPIO0
