esphome:
  name: power-meter-9000
  friendly_name: power-meter-9000
  name_add_mac_suffix: true

esp32:
  board: lolin_s2_mini
  framework:
    type: arduino

# Enable logging
logger:
  level: WARN

api:

ota:

wifi:
  output_power: 8.5

  # Enable hotspot (captive portal) to provision WiFi
  ap:
    ssid: power-meter-9000
    password: power-meter-9000

captive_portal:

uart:
  tx_pin: GPIO40
  rx_pin: GPIO39
  baud_rate: 4800
  parity: NONE
  stop_bits: 1

external_components:
    source: github://ggajoch/power-meter-9000

sensor:
  - platform: uptime
    name: Uptime
  - platform: bl0939addr
    id: chA
    update_interval: 10s
    voltage:
      name: 'v_A'
    current_1:
      name: 'c_A1'
    current_2:
      name: 'c_A2'
    active_power_1:
      name: 'p_A1'
    active_power_2:
      name: 'p_A2'
    energy_1:
      name: 'e_A1'
    energy_2:
      name: 'e_A2'
    energy_total:
      name: 'e_A'
    address: 0
    current_reference: 438921.675
    voltage_reference: 16740.165
    power_reference: 1147.908
    energy_reference: 9852.572

  - platform: bl0939addr
    id: ch1
    update_interval: 10s
    voltage:
      name: 'v_B'
    current_1:
      name: 'c_B1'
    current_2:
      name: 'c_B2'
    active_power_1:
      name: 'p_B1'
    active_power_2:
      name: 'p_B2'
    energy_1:
      name: 'e_B1'
    energy_2:
      name: 'e_B2'
    energy_total:
      name: 'e_B'
    address: 1
    current_reference: 438921.675
    voltage_reference: 16740.165
    power_reference: 1147.908
    energy_reference: 9852.572
  
  - platform: bl0939addr
    id: ch2
    update_interval: 10s
    voltage:
      name: 'v_C'
    current_1:
      name: 'c_C1'
    current_2:
      name: 'c_C2'
    active_power_1:
      name: 'p_C1'
    active_power_2:
      name: 'p_C2'
    energy_1:
      name: 'e_C1'
    energy_2:
      name: 'e_C2'
    energy_total:
      name: 'e_C'
    address: 2
    current_reference: 438921.675
    voltage_reference: 16740.165
    power_reference: 1147.908
    energy_reference: 9852.572

  - platform: bl0939addr
    id: ch3
    update_interval: 10s
    voltage:
      name: 'v_D'
    current_1:
      name: 'c_D1'
    current_2:
      name: 'c_D2'
    active_power_1:
      name: 'p_D1'
    active_power_2:
      name: 'p_D2'
    energy_1:
      name: 'e_D1'
    energy_2:
      name: 'e_D2'
    energy_total:
      name: 'e_D'
    address: 3
    current_reference: 438921.675
    voltage_reference: 16740.165
    power_reference: 1147.908
    energy_reference: 9852.572

switch:
  - platform: gpio
    pin: 15
    name: "LED"

binary_sensor:
  - platform: gpio
    name: "button"
    pin: GPIO0
